-- ============================================
-- DailyBits: AI-Powered Python Practice Platform
-- Database: PostgreSQL (for Supabase)
-- ============================================

DROP DATABASE IF EXISTS dailybits;
CREATE DATABASE dailybits;

\c dailybits;

-- ============================================
-- USER & ACCOUNT TABLES
-- ============================================
CREATE TABLE user_profile (
    email VARCHAR(100) PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL
);

CREATE TABLE user_auth (
    email VARCHAR(100) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    FOREIGN KEY (email) REFERENCES user_profile (email) ON DELETE CASCADE
);

CREATE TABLE account (
    account_number SERIAL PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    register_date DATE NOT NULL DEFAULT CURRENT_DATE,
    student_flag BOOLEAN DEFAULT TRUE,
    admin_flag BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (email) REFERENCES user_profile (email) ON DELETE CASCADE
);

CREATE TABLE token_blacklist (
    jti VARCHAR(255) PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    expired_at TIMESTAMP NOT NULL,
    FOREIGN KEY (email) REFERENCES user_profile(email) ON DELETE CASCADE
);


-- ============================================
-- PROBLEM & SOLUTION TABLES (Python Problems)
-- ============================================
CREATE TABLE problem (
    problem_id        SERIAL PRIMARY KEY,
    difficulty_level  VARCHAR(10) NOT NULL
        CHECK (difficulty_level IN ('Easy', 'Medium', 'Hard')),
    problem_title     VARCHAR(200) NOT NULL,
    problem_description TEXT NOT NULL,
    starter_code      TEXT,
    is_published      BOOLEAN DEFAULT FALSE,
    estimate_time_baseline INT
);

CREATE TABLE solution (
    solution_id         SERIAL PRIMARY KEY,
    problem_id          INT NOT NULL UNIQUE,
    solution_code       TEXT NOT NULL,
    solution_explanation TEXT,
    time_complexity     VARCHAR(50),
    space_complexity    VARCHAR(50),
    is_published        BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (problem_id) REFERENCES problem (problem_id) ON DELETE CASCADE
);

CREATE TABLE problem_example (
    problem_id INT REFERENCES problem (problem_id) ON DELETE CASCADE,
    example_id SERIAL,
    example_input TEXT NOT NULL,
    example_output TEXT NOT NULL,
    example_explanation TEXT,
    PRIMARY KEY (problem_id, example_id)
);

CREATE TABLE problem_constraint (
    problem_id INT REFERENCES problem (problem_id) ON DELETE CASCADE,
    constraint_id SERIAL,
    problem_constraint TEXT NOT NULL,
    PRIMARY KEY (problem_id, constraint_id) 
);

-- ============================================
-- TAG TABLES (Algorithm Categories)
-- ============================================
CREATE TABLE algorithm (
    algorithm_id SERIAL PRIMARY KEY,
    algorithm_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE problem_algorithm (
    problem_id INT REFERENCES problem (problem_id) ON DELETE CASCADE,
    algorithm_id INT REFERENCES algorithm (algorithm_id) ON DELETE CASCADE,
    PRIMARY KEY (problem_id, algorithm_id)
);


-- ============================================
-- SUBMISSION 
-- ============================================
CREATE TABLE submission (
    submission_id  SERIAL PRIMARY KEY,
    problem_id     INT NOT NULL,
    account_number INT NOT NULL,
    submitted_code TEXT NOT NULL,
    is_correct     BOOLEAN NOT NULL,
    submitted_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (problem_id)     REFERENCES problem (problem_id) ON DELETE CASCADE,
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE
);


-- ============================================
-- STUDY PLAN (Gemini for Study Plans)
-- ============================================
-- Study Plan Generated by AI
CREATE TABLE study_plan (
    plan_id SERIAL PRIMARY KEY,
    account_number INT NOT NULL,
    plan_name VARCHAR(200) NOT NULL,
    time_available INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_accepted BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE
);

-- Problems included in a study plan
CREATE TABLE study_plan_problems (
    plan_id INT,
    problem_id INT,
    estimate_time_assigned INT NOT NULL, 
    PRIMARY KEY (plan_id, problem_id),
    FOREIGN KEY (plan_id) REFERENCES study_plan (plan_id) ON DELETE CASCADE,
    FOREIGN KEY (problem_id) REFERENCES problem (problem_id) ON DELETE CASCADE
);

-- Algorithm selections for study plan
CREATE TABLE study_plan_algorithm (
    plan_id      INT REFERENCES study_plan (plan_id) ON DELETE CASCADE,
    algorithm_id INT REFERENCES algorithm (algorithm_id) ON DELETE CASCADE,
    PRIMARY KEY (plan_id, algorithm_id)
);

-- Difficulty selections for study plan
CREATE TABLE study_plan_difficulty (
    plan_id INT REFERENCES study_plan (plan_id) ON DELETE CASCADE,
    difficulty_level VARCHAR(10) NOT NULL
                         CHECK (difficulty_level IN ('Easy', 'Medium', 'Hard')),
    PRIMARY KEY (plan_id, difficulty_level)
);

-- Chat Query Table (for AI assistant interactions)
CREATE TABLE chat_query (
    query_id SERIAL PRIMARY KEY,
    account_number INT NOT NULL,
    user_message TEXT NOT NULL,
    ai_response TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE
);


-- ============================================
-- One unified todo list per user.
-- Each item references a problem and optionally the study plan it came from.
-- source: 'manual' = user added directly, 'study_plan' = imported from AI plan

CREATE TABLE todo_item (
    todo_id        SERIAL PRIMARY KEY,
    account_number INT NOT NULL,
    problem_id     INT NOT NULL,
    plan_id        INT,
    source         VARCHAR(20) NOT NULL DEFAULT 'manual'
                       CHECK (source IN ('manual', 'study_plan')),
    added_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE,
    FOREIGN KEY (problem_id)     REFERENCES problem (problem_id)     ON DELETE CASCADE,
    FOREIGN KEY (plan_id)        REFERENCES study_plan (plan_id)     ON DELETE SET NULL
);


-- ============================================
-- STUDY NOTES TABLE
-- ============================================
-- Users can write/edit one note per todo item at any time (pending or completed).
-- Stored separately so the todo_item row stays lean.
-- On hard delete of a todo_item, note is also deleted (CASCADE).

CREATE TABLE study_note (
    note_id         SERIAL PRIMARY KEY,
    todo_id         INT NOT NULL UNIQUE,          -- one note per todo item
    account_number  INT NOT NULL,
    note_content    TEXT NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (todo_id)        REFERENCES todo_item (todo_id) ON DELETE CASCADE,
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE
);


-- ============================================
-- INDEXES
-- ============================================
-- Solution
CREATE INDEX idx_solution_problem_id ON solution (problem_id);

-- Submission
CREATE INDEX idx_submission_account ON submission (account_number);
CREATE INDEX idx_submission_account_problem ON submission (account_number, problem_id);

-- Study Plan
CREATE INDEX idx_study_plan_account ON study_plan (account_number);

-- Problem Algorithm (used heavily in views)
CREATE INDEX idx_problem_algorithm_problem ON problem_algorithm (problem_id);
CREATE INDEX idx_problem_algorithm_algorithm ON problem_algorithm (algorithm_id);

-- Todo Item
CREATE INDEX idx_todo_account ON todo_item (account_number);
CREATE INDEX idx_todo_plan ON todo_item (plan_id);

-- Study Note
CREATE INDEX idx_study_note_todo ON study_note (todo_id);

-- Problem Example and Constraint
CREATE INDEX idx_problem_example_problem ON problem_example (problem_id);
CREATE INDEX idx_problem_constraint_problem ON problem_constraint (problem_id);

-- ============================================
-- VIEWS
-- ============================================
-- Problem Library View
-- Shows all published problems with aggregated algorithm tags
-- Used by: Problem library page (all users)
CREATE VIEW user_problem_library_view AS
SELECT
    p.problem_id,
    p.problem_title,
    p.problem_description,
    p.difficulty_level,
    p.estimate_time_baseline,
    array_agg(a.algorithm_name) AS algorithms
FROM problem p
JOIN problem_algorithm pa ON p.problem_id = pa.problem_id
JOIN algorithm a          ON pa.algorithm_id = a.algorithm_id
WHERE p.is_published = TRUE
GROUP BY
    p.problem_id,
    p.problem_title,
    p.problem_description,
    p.difficulty_level,
    p.estimate_time_baseline;

-- Problem Library View
-- Shows all problems with aggregated algorithm tags
-- Used by: Problem edit page (admin only)
CREATE VIEW admin_problem_library_view AS
SELECT
    p.problem_id,
    p.problem_title,
    p.problem_description,
    p.difficulty_level,
    p.estimate_time_baseline,
    p.is_published,
    COALESCE(
        array_agg(a.algorithm_name) FILTER (WHERE a.algorithm_name IS NOT NULL),
        ARRAY[]::VARCHAR(50)[]
    ) AS algorithms
FROM problem p
LEFT JOIN problem_algorithm pa ON p.problem_id = pa.problem_id
LEFT JOIN algorithm a          ON pa.algorithm_id = a.algorithm_id
GROUP BY
    p.problem_id,
    p.problem_title,
    p.problem_description,
    p.difficulty_level,
    p.estimate_time_baseline,
    p.is_published;

-- Todo List View
-- Shows all todo items for a user with problem details and aggregated algorithms
-- Completion status derived from submission table, not stored
-- Used by: Todo list page (per user)
CREATE VIEW todo_list_view AS
SELECT
    t.todo_id,
    t.account_number,
    t.problem_id,
    p.problem_title,
    p.problem_description,
    p.difficulty_level,
    t.added_at,
    array_agg(a.algorithm_name) AS algorithms,
    EXISTS (
        SELECT 1 FROM submission s
        WHERE s.account_number = t.account_number
          AND s.problem_id = t.problem_id
          AND s.is_correct = TRUE
    ) AS is_completed
FROM todo_item t
JOIN problem p             ON t.problem_id   = p.problem_id
JOIN problem_algorithm pa  ON p.problem_id   = pa.problem_id
JOIN algorithm a           ON pa.algorithm_id = a.algorithm_id
GROUP BY
    t.todo_id,
    t.account_number,
    t.problem_id,
    p.problem_title,
    p.problem_description,
    p.difficulty_level,
    t.added_at;

-- Single Problem View
-- Show single problem in details 
CREATE VIEW single_problem_view AS
SELECT
    p.problem_id,
    p.problem_title,
    p.problem_description,
    p.difficulty_level,
    p.starter_code,
    p.estimate_time_baseline,
    alg.algorithms,
    con.problem_constraints,
    ex.examples
FROM problem p
JOIN (
    SELECT pa.problem_id,
           array_agg(DISTINCT a.algorithm_name) AS algorithms
    FROM problem_algorithm pa
    JOIN algorithm a ON pa.algorithm_id = a.algorithm_id
    GROUP BY pa.problem_id
) alg ON p.problem_id = alg.problem_id
JOIN (
    SELECT problem_id,
           array_agg(DISTINCT problem_constraint) AS problem_constraints
    FROM problem_constraint
    GROUP BY problem_id
) con ON p.problem_id = con.problem_id
JOIN (
    SELECT problem_id,
           json_agg(json_build_object(
               'input',       example_input,
               'output',      example_output,
               'explanation', example_explanation
           )) AS examples
    FROM problem_example
    GROUP BY problem_id
) ex ON p.problem_id = ex.problem_id;

-- ============================================
-- ANALYTICS VIEWS
-- ============================================
-- User Progress View
-- Powers: top 4 cards + progress by difficulty chart
-- Django filters by account_number when querying
CREATE VIEW user_progress_view AS
SELECT
    a.account_number,

    -- Total problems solved (distinct to avoid counting multiple correct submissions)
    COUNT(DISTINCT CASE WHEN s.is_correct = TRUE THEN s.problem_id END)
        AS problems_solved,

    -- Total unique practice days
    COUNT(DISTINCT s.submitted_at::DATE)
        AS total_practice_days,

    -- Most recent practice date
    MAX(s.submitted_at::DATE)
        AS last_practice_date,

    -- Number of problems in todo list
    (SELECT COUNT(*) FROM todo_item t WHERE t.account_number = a.account_number)
        AS todo_count,

    -- Problems solved per difficulty
    COUNT(DISTINCT CASE WHEN p.difficulty_level = 'Easy'   AND s.is_correct = TRUE THEN s.problem_id END)
        AS easy_solved,
    COUNT(DISTINCT CASE WHEN p.difficulty_level = 'Medium' AND s.is_correct = TRUE THEN s.problem_id END)
        AS medium_solved,
    COUNT(DISTINCT CASE WHEN p.difficulty_level = 'Hard'   AND s.is_correct = TRUE THEN s.problem_id END)
        AS hard_solved,

    -- Total published problems per difficulty (same for all users)
    (SELECT COUNT(*) FROM problem WHERE difficulty_level = 'Easy'   AND is_published = TRUE) AS easy_total,
    (SELECT COUNT(*) FROM problem WHERE difficulty_level = 'Medium' AND is_published = TRUE) AS medium_total,
    (SELECT COUNT(*) FROM problem WHERE difficulty_level = 'Hard'   AND is_published = TRUE) AS hard_total

FROM account a
LEFT JOIN submission s ON a.account_number = s.account_number
LEFT JOIN problem p    ON s.problem_id = p.problem_id
GROUP BY a.account_number;

-- User Recent Activity View
-- Powers: recent activity section (Django applies LIMIT 5 and filters by account_number)
-- Returns most recent submission per distinct problem per user
CREATE VIEW user_recent_activity_view AS
SELECT DISTINCT ON (s.account_number, s.problem_id)
    s.account_number,
    p.problem_id,
    p.problem_title,
    p.difficulty_level,
    s.submitted_at,
    s.is_correct
FROM submission s
JOIN problem p ON s.problem_id = p.problem_id
ORDER BY s.account_number, s.problem_id, s.submitted_at DESC;

-- User Algorithm Progress View
-- Powers: problems completed by algorithm chart (Option B — shows all algorithms including 0)
-- Django filters by account_number when querying
CREATE VIEW user_algorithm_progress_view AS
SELECT
    a.account_number,
    alg.algorithm_id,
    alg.algorithm_name,

    -- Count of distinct problems solved per algorithm per user
    COUNT(DISTINCT CASE WHEN s.is_correct = TRUE THEN s.problem_id END)
        AS problems_solved

FROM account a
CROSS JOIN algorithm alg
LEFT JOIN problem_algorithm pa  ON alg.algorithm_id  = pa.algorithm_id
LEFT JOIN problem p             ON pa.problem_id      = p.problem_id
                                AND p.is_published    = TRUE
LEFT JOIN submission s          ON p.problem_id       = s.problem_id
                                AND s.account_number  = a.account_number
GROUP BY a.account_number, alg.algorithm_id, alg.algorithm_name
ORDER BY alg.algorithm_name;


-- ============================================
-- FUNCTIONS
-- ============================================
-- Accept Study Plan -> Bulk insert problems into todo_item
-- Called when user clicks "Accept Plan" on the study plan page
-- Duplicate checking handled in Django before calling this function
CREATE OR REPLACE FUNCTION accept_study_plan(
    p_account_number INT,
    p_plan_id        INT
)
RETURNS void AS $$
BEGIN
    INSERT INTO todo_item (account_number, problem_id, plan_id, source)
    SELECT
        p_account_number,
        spp.problem_id,
        p_plan_id,
        'study_plan'
    FROM study_plan_problems spp
    WHERE spp.plan_id = p_plan_id;
END;
$$ LANGUAGE plpgsql;


-- ============================================
-- TRIGGERS
-- ============================================
-- Trigger: Auto-update updated_at on study_note when note content is edited
CREATE OR REPLACE FUNCTION refresh_study_note_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_study_note_updated_at
BEFORE UPDATE ON study_note
FOR EACH ROW
WHEN (OLD.note_content IS DISTINCT FROM NEW.note_content)
EXECUTE FUNCTION refresh_study_note_updated_at();

-- Publishing Validation
-- Trigger 1: Prevent publishing a solution if its problem is not published
CREATE OR REPLACE FUNCTION check_solution_publish()
RETURNS TRIGGER AS $$
DECLARE
    v_problem_published BOOLEAN;
BEGIN
    IF NEW.is_published = TRUE THEN
        SELECT is_published INTO v_problem_published
        FROM problem
        WHERE problem_id = NEW.problem_id;

        IF v_problem_published = FALSE THEN
            RAISE EXCEPTION 'Cannot publish solution: problem % is not published yet', 
                NEW.problem_id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_solution_publish
BEFORE UPDATE ON solution
FOR EACH ROW
EXECUTE FUNCTION check_solution_publish();

-- Trigger 2: Prevent publishing a problem if it has no solution
CREATE OR REPLACE FUNCTION check_problem_publish()
RETURNS TRIGGER AS $$
DECLARE
    v_solution_exists BOOLEAN;
BEGIN
    IF NEW.is_published = TRUE THEN
        SELECT EXISTS (
            SELECT 1 FROM solution
            WHERE problem_id = NEW.problem_id
        ) INTO v_solution_exists;

        IF v_solution_exists = FALSE THEN
            RAISE EXCEPTION 'Cannot publish problem %: no solution exists yet', 
                NEW.problem_id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_problem_publish
BEFORE UPDATE ON problem
FOR EACH ROW
EXECUTE FUNCTION check_problem_publish();
