-- ============================================
-- DailyBits: AI-Powered Python Practice Platform
-- Database: PostgreSQL (for Supabase)
-- ============================================

DROP DATABASE IF EXISTS dailybits;
CREATE DATABASE dailybits;

\c dailybits;

-- ============================================
-- USER & ACCOUNT TABLES
-- ============================================
CREATE TABLE user_profile (
    email VARCHAR(100) PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL
);

CREATE TABLE user_auth (
    email VARCHAR(100) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    FOREIGN KEY (email) REFERENCES user_profile (email) ON DELETE CASCADE
);

CREATE TABLE account (
    account_number SERIAL PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    register_date DATE NOT NULL DEFAULT CURRENT_DATE,
    student_flag BOOLEAN DEFAULT TRUE,
    admin_flag BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (email) REFERENCES user_profile (email) ON DELETE CASCADE
);

-- ============================================
-- TAG TABLES (Algorithm Categories)
-- ============================================
CREATE TABLE difficulty_tag (
    difficulty_id SERIAL PRIMARY KEY,
    difficulty_level VARCHAR(10) NOT NULL UNIQUE 
        CHECK (difficulty_level IN ('Easy', 'Medium', 'Hard'))
);

CREATE TABLE concept_tag (
    concept_id SERIAL PRIMARY KEY,
    concept_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE tag (
    tag_id SERIAL PRIMARY KEY,
    difficulty_id INT NOT NULL,
    concept_id INT NOT NULL,
    FOREIGN KEY (difficulty_id) REFERENCES difficulty_tag (difficulty_id),
    FOREIGN KEY (concept_id) REFERENCES concept_tag (concept_id),
    UNIQUE (difficulty_id, concept_id)
);

-- ============================================
-- PROBLEM & SOLUTION TABLES (Python Problems)
-- ============================================
CREATE TABLE problem (
    problem_id SERIAL PRIMARY KEY,
    tag_id INT,
    problem_title VARCHAR(200) NOT NULL,
    problem_description TEXT NOT NULL,
    function_signature TEXT,
    starter_code TEXT,
    review_status BOOLEAN DEFAULT FALSE,
    solution_id INT,
    FOREIGN KEY (tag_id) REFERENCES tag (tag_id)
);

CREATE TABLE solution (
    solution_id SERIAL PRIMARY KEY,
    problem_id INT,
    solution_code TEXT NOT NULL,
    solution_explanation TEXT,
    time_complexity VARCHAR(50),
    space_complexity VARCHAR(50),
    review_status BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (problem_id) REFERENCES problem (problem_id) ON DELETE CASCADE
);

-- ============================================
-- SUBMISSION & ATTEMPT TABLES
-- ============================================
CREATE TABLE submission (
    submission_id SERIAL PRIMARY KEY,
    problem_id INT NOT NULL,
    account_number INT NOT NULL,
    submitted_code TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    time_start TIMESTAMP NOT NULL,
    time_end TIMESTAMP NOT NULL,
    FOREIGN KEY (problem_id) REFERENCES problem (problem_id) ON DELETE CASCADE,
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE,
    CHECK (time_end >= time_start)
);

CREATE TABLE attempt (
    attempt_id SERIAL PRIMARY KEY,
    problem_id INT NOT NULL,
    account_number INT NOT NULL,
    attempt_number INT NOT NULL,
    is_submitted BOOLEAN DEFAULT FALSE,
    submission_id INT,
    FOREIGN KEY (problem_id) REFERENCES problem (problem_id),
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE,
    FOREIGN KEY (submission_id) REFERENCES submission (submission_id),
    UNIQUE (problem_id, account_number, attempt_number),
    CHECK (attempt_number > 0)
);

-- ============================================
-- PROGRESS TRACKING TABLE
-- ============================================
CREATE TABLE user_progress (
    progress_id SERIAL PRIMARY KEY,
    account_number INT UNIQUE NOT NULL,
    total_problems_attempted INT DEFAULT 0,
    total_problems_solved INT DEFAULT 0,
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE
);

-- ============================================
-- LLM TABLES (Gemini for Study Plans)
-- ============================================
CREATE TABLE llm (
    model_id SERIAL PRIMARY KEY,
    model_name VARCHAR(50) NOT NULL
);

-- Study Plan Generated by AI
CREATE TABLE study_plan (
    plan_id SERIAL PRIMARY KEY,
    account_number INT NOT NULL,
    model_id INT,
    plan_name VARCHAR(200) NOT NULL,
    focus_area VARCHAR(100),
    time_available INT,
    difficulty_preference VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE,
    FOREIGN KEY (model_id) REFERENCES llm (model_id)
);

-- Problems included in a study plan
CREATE TABLE study_plan_problems (
    plan_id INT,
    problem_id INT,
    day_number INT,
    PRIMARY KEY (plan_id, problem_id),
    FOREIGN KEY (plan_id) REFERENCES study_plan (plan_id) ON DELETE CASCADE,
    FOREIGN KEY (problem_id) REFERENCES problem (problem_id) ON DELETE CASCADE
);

-- Chat Query Table (for AI assistant interactions)
CREATE TABLE chat_query (
    query_id SERIAL PRIMARY KEY,
    account_number INT NOT NULL,
    model_id INT,
    user_message TEXT NOT NULL,
    ai_response TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_number) REFERENCES account (account_number) ON DELETE CASCADE,
    FOREIGN KEY (model_id) REFERENCES llm (model_id)
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX idx_solution_problem_id ON solution (problem_id);
CREATE INDEX idx_attempt_account_number ON attempt (account_number);
CREATE INDEX idx_attempt_problem ON attempt (problem_id);
CREATE INDEX idx_submission_account ON submission (account_number);
CREATE INDEX idx_study_plan_account ON study_plan (account_number);
CREATE INDEX idx_problem_tag ON problem (tag_id);

-- ============================================
-- VIEWS
-- ============================================
-- Admin view
CREATE VIEW admin_list AS
SELECT first_name, last_name, email
FROM user_profile
WHERE email IN (SELECT email FROM account WHERE admin_flag = TRUE);

-- Problem review status view
CREATE VIEW pending_problem_review AS
SELECT 
    p.problem_id,
    p.problem_title,
    p.problem_description,
    d.difficulty_level,
    c.concept_name,
    p.review_status
FROM problem p
JOIN tag t ON p.tag_id = t.tag_id
JOIN difficulty_tag d ON t.difficulty_id = d.difficulty_id
JOIN concept_tag c ON t.concept_id = c.concept_id
WHERE p.review_status = FALSE;

-- Solution review status view
CREATE VIEW pending_solution_review AS
SELECT 
    s.solution_id,
    s.solution_code,
    p.problem_id,
    p.problem_title,
    s.review_status
FROM solution s
JOIN problem p ON s.problem_id = p.problem_id
WHERE s.review_status = FALSE;

-- User progress summary view
CREATE VIEW user_progress_summary AS
SELECT 
    a.account_number,
    up.first_name,
    up.last_name,
    prog.total_problems_attempted,
    prog.total_problems_solved,
    CASE 
        WHEN prog.total_problems_attempted > 0 
        THEN ROUND((prog.total_problems_solved::DECIMAL / prog.total_problems_attempted) * 100, 2)
        ELSE 0
    END AS success_rate
FROM account a
JOIN user_profile up ON a.email = up.email
LEFT JOIN user_progress prog ON a.account_number = prog.account_number;

-- ============================================
-- TRIGGERS
-- ============================================
-- Trigger: Update attempt after correct submission
CREATE OR REPLACE FUNCTION update_attempt_on_submission()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_correct = TRUE THEN
        UPDATE attempt
        SET is_submitted = TRUE,
            submission_id = NEW.submission_id
        WHERE problem_id = NEW.problem_id
          AND account_number = NEW.account_number
          AND attempt_number = (
              SELECT MAX(attempt_number)
              FROM attempt
              WHERE problem_id = NEW.problem_id
                AND account_number = NEW.account_number
                AND submission_id IS NULL
          );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_correct_submission
AFTER INSERT ON submission
FOR EACH ROW
EXECUTE FUNCTION update_attempt_on_submission();

-- Trigger: Update user progress when problem is solved
CREATE OR REPLACE FUNCTION update_user_progress()
RETURNS TRIGGER AS $$
BEGIN
    -- Insert progress record if it doesn't exist
    INSERT INTO user_progress (account_number, total_problems_attempted, total_problems_solved)
    VALUES (NEW.account_number, 0, 0)
    ON CONFLICT (account_number) DO NOTHING;
    
    -- Update progress
    IF NEW.is_correct = TRUE THEN
        UPDATE user_progress
        SET total_problems_solved = total_problems_solved + 1,
            total_problems_attempted = total_problems_attempted + 1
        WHERE account_number = NEW.account_number;
    ELSE
        UPDATE user_progress
        SET total_problems_attempted = total_problems_attempted + 1
        WHERE account_number = NEW.account_number;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_submission_update_progress
AFTER INSERT ON submission
FOR EACH ROW
EXECUTE FUNCTION update_user_progress();

-- ============================================
-- FUNCTIONS (replacing stored procedures)
-- ============================================
-- Get student success rate
CREATE OR REPLACE FUNCTION get_student_success_rate(input_account_number INT)
RETURNS TABLE (
    total_attempts BIGINT,
    successful_submissions BIGINT,
    success_rate DECIMAL(5,2)
) AS $$
DECLARE
    v_total_attempts BIGINT;
    v_successful_submissions BIGINT;
    v_success_rate DECIMAL(5,2);
BEGIN
    -- Calculate total attempts
    SELECT COUNT(*) INTO v_total_attempts
    FROM attempt
    WHERE account_number = input_account_number;
    
    -- Calculate successful submissions
    SELECT COUNT(*) INTO v_successful_submissions
    FROM submission
    WHERE account_number = input_account_number
      AND is_correct = TRUE;
    
    -- Calculate success rate
    IF v_total_attempts > 0 THEN
        v_success_rate := (v_successful_submissions::DECIMAL / v_total_attempts) * 100;
    ELSE
        v_success_rate := 0;
    END IF;
    
    RETURN QUERY SELECT v_total_attempts, v_successful_submissions, v_success_rate;
END;
$$ LANGUAGE plpgsql;